___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1


#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [1]:
import numpy as np

Вивести версію та конфігурацію бібліотеки:

In [3]:
print(np.__version__)
np.show_config()

1.21.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

Створити вектор з 10 елементів, заповнений одиницями:

In [4]:
Z = np.ones(10)
print(Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Створити вектор із значеннями від 0 до 10:

In [6]:
Z = np.arange(0,11)
print(Z)

[ 0  1  2  3  4  5  6  7  8  9 10]


Створити матрицю 5 на 5, заповнену нулями:

In [7]:
Z = np.zeros(25).reshape(5,5)
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:

In [27]:
Z = np.random.randint(0, 3, 20)
nz = np.nonzero(Z)
print(nz)

(array([ 0,  1,  2,  5,  8,  9, 11, 13, 14, 16, 17, 18, 19]),)


Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [28]:
m=np.mean(Z)
med=np.median(Z)
std=np.std(Z)

print(m,med,std)

0.95 1.0 0.8046738469715541


Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [33]:
m1 = np.random.randint(0, 10, 8).reshape(4,2)
m2= np.random.randint(0, 10, 4).reshape(2,2)
total = m1.dot(m2)
print(total)


[[26 49]
 [24 74]
 [42 53]
 [28  7]]


Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

Максимальне значення замінити на 0:

In [55]:
res=total.flatten()
max=np.max(res)
min=np.min(res)
print(min, max)
ind=np.argmax(res)
res[ind]=0
print(res)

7 74
[26 49 24  0 42 53 28  7]


Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

In [100]:
c2 = np.random.randint(0, 10, 8)
c = np.corrcoef(res, c2)

c

Дано матрицю. Знайти ранг матриці:

In [56]:
a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])
dfg=np.linalg.matrix_rank(a)
print(dfg)

3


Знайти визначник матриці:

In [58]:
det=np.linalg.det(a)
print(round(det))

440


Знайти власні значення та власні вектори матриці: 

In [62]:
eigenvalue,featurevector=np.linalg.eig(a)
print ("Собственные значения исходной матрицы")
print("eigenvalue=",eigenvalue)
print("featurevector=",featurevector)

Собственные значения исходной матрицы
eigenvalue= [14.13520334+0.j         -4.56760167+3.20389947j -4.56760167-3.20389947j]
featurevector= [[ 0.43131913+0.j         -0.31386258-0.47450898j -0.31386258+0.47450898j]
 [ 0.41502436+0.j         -0.07049527+0.4090732j  -0.07049527-0.4090732j ]
 [ 0.8010734 +0.j          0.7099444 +0.j          0.7099444 -0.j        ]]


Знайдіть число, що найчастіше зустрічається в масиві:

In [72]:
a = np.random.randint(0,10,50)

d = np.argmax(np.bincount(a))
d

8

Виведіть лише парні числа, що діляться на 5:

In [77]:
a = np.random.randint(0,10,50)
a=a[a%5==0]
a

Розв'яжіть систему рівнянь:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [78]:
M1 = np.array([[2., 5.], [1., -10.]]) 
v1 = np.array([1., 3.])
solve=np.linalg.solve(M1, v1)
solve